fail_fast: false
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.7
    hooks:
      - id: ruff # linter
        args: ["--ignore", "FIX002"]
      - id: ruff-format # formatter
